spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.use_nationalized_character_data]': true
      '[javax.persistence.schema-generation.scripts.action]': none
      '[javax.persistence.schema-generation.scripts.create-target]': create.sql
      '[javax.persistence.schema-generation.scripts.drop-target]': drop.sql
      '[javax.persistence.schema-generation.create-source]': metadata
      '[javax.persistence.schema-generation.drop-source]': metadata

logging:
  level:
    root: info
    jdbc: warn

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  sqltiming:
    warn:
      threshold: 50
    error:
      threshold: 300
