spring:
  mandatory-file-encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.jdbc.time_zone]': UTC
      '[hibernate.use_nationalized_character_data]': true
  mail:
    host: localhost
    port: 2525
    properties:
      mail:
        smtp:
          ssl:
            enable: false
          starttls:
            enable: false
  freemarker:
    cache: true
    settings:
      '[template_exception_handler]': rethrow
      '[number_format]': computer

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  info:
    git:
      mode: full

logging:
  level:
    root: info
    jdbc: warn

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  sqltiming:
    warn:
      threshold: 50
    error:
      threshold: 300
---
spring:
  config:
    activate:
      on-profile: jpa-scripts
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      '[jakarta.persistence.schema-generation.scripts.action]': create
      '[jakarta.persistence.schema-generation.scripts.create-target]': create.sql
      '[jakarta.persistence.schema-generation.scripts.drop-target]': drop.sql
      '[jakarta.persistence.schema-generation.create-source]': metadata
      '[jakarta.persistence.schema-generation.drop-source]': metadata
